name: Deploy Vue Project

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Enable Corepack and activate pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Vue project
        run: pnpm run build

      - name: Upload dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          # 如果用密钥登录，改成下面一行，注释掉 password
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: ./dist/*
          target: /www/server/vue-app/dist

      - name: Run remote hot reload commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          # 如果用密钥登录，改成下面一行，注释掉 password
          # key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            # 下面示例为 pm2 重启服务，或 nginx reload，根据你实际情况替换
            pm2 reload vue-app || echo "pm2 reload failed, maybe app not managed by pm2"
            # 或者 nginx reload
            # sudo nginx -s reload
