name: Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
          cache-dependency-path: ./pnpm-lock.yaml

      - name: Enable Corepack and Activate PNPM
        run: |
          corepack enable
          corepack prepare pnpm@9.1.1 --activate

      - name: Verify pnpm version
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Upload to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "./dist/*"
          target: "/www/server/nginx/html/blog_front_v3"
